### ISSUE TITLE
Removal of PojavLauncher

### ISSUE THREAD

**Issue by crystall1nedev** [The-SamminAter/repo#1]
Hello 👋. I'm here to inform you that we (PojavLauncherTeam) would like you to remove PojavLauncher from your repository. Although our license permits you to distribute the launcher, we recommend that it be removed and have some important notes to point out why:

1. The purpose that your repo served to deliver PojavLauncher directly to users has been fulfilled, with Procursus and my own repository hosting copies of the launcher (and my repository with the always updating development builds).

2. We wish to have all repos that distribute PojavLauncher be verified and signed with a GPG key, which would be available for users to install from Procursus or with the repository itself. This is due to recent malware scares in the community (man-in-the-middle is what we are getting at, not you distributing malware).

If you want to see about not being pushed to remove, you can contact me for more information (my email is on my profile).

**Comment by The-SamminAter** [comment]
Completed, PojavLauncher has been removed from the Packages file and the index.html. Is that sufficient?

**Comment by crystall1nedev** [comment]
Should be, thank you for responding so quick.

**Comment by The-SamminAter** [comment]
No problem. Unless you object, I'm going to close this issue now.

**Comment by crystall1nedev** [comment]
I do not
